Activity.create({country: "Japan", name: "Ashikaga Flower Park", description: "The Japanese love flowers, and wisteria are among their favorites. Wisteria are called fuji in Japanese, like Mt. Fuji, but unlike the mountain, the flower is pronounced by stressing the second syllable. One of the best places to view fuji flowers is the Ashikaga Flower Park (あしかがフラワーパーク) in Ashikaga City, Tochigi Prefecture. Ashikaga Flower Park features lots of blue, white and pink fuji, as well as yellow laburnum (Japanese: kingusari) that look like yellow colored fuji. One large fuji tree is 100 years old and its branches are supported to create a huge umbrella of blue fuji flowers. There is also a long tunnel of white fuji flowers, while a tunnel of yellow kingusari needs a few more years to become an actual tunnel. Yae-fuji, a variety with more than the usual number of petals, can also be viewed.", address: "Japan, 〒329-4216 Tochigi Prefecture, Ashikaga, Hasamacho, ６０7", image_url: "https://i.imgur.com/DH8mqgJ.jpg"})

Activity.create({country: "Japan", name: "Mount Rokko", description: "Mount Rokko (六甲山, Rokkōsan, 931 meters) is the highest peak in the Rokko mountain range, which provides the pleasant green backdrop to the city of Kobe. Panoramic views of the heavily urbanized Hanshin region (Kobe and Osaka) can be enjoyed from the mountain and are particularly spectacular around sunset. Various small tourist attractions can be found on Mount Rokko, including a botanical garden, a music box museum, a pasture with flowers and sheep, Japan's first golf course and Rokko Garden Terrace, a tourist complex with a few restaurants, shops and an observation deck.", address: "Motoyamachomori, Higashinada Ward, Kobe, Hyōgo 658-0000, Japan", image_url: "https://www.halalinjapan.com/uploads/2/5/6/3/25635777/640px-rokko-garden-terrace03s3200_orig.jpg"})

Activity.create({country: "Japan", name: "Fushimi Inari-Taisha Shrine", description: "This intriguing shrine was dedicated to the god of rice and sake by the Hata clan in the 8th century. As the role of agriculture diminished, deities were enrolled to ensure prosperity in business enterprises. The magical, seemingly unending path of over 5000 vibrant orange torii gates that wind through the hills behind Fushimi Inari-taisha Shrine makes it one of the most popular shrines in Japan. The walk around the upper precincts is a pleasant day hike. It also makes for a delightfully eerie stroll in the late afternoon and early evening, when the various graveyards and miniature shrines along the path take on a mysterious air.", address: "68 Fukakusa Yabunouchichō, Fushimi-ku, Kyōto-shi, Kyōto-fu 612-0882, Japan", image_url: "https://i.imgur.com/355JktA.jpg"})

Activity.create({country: "Japan", name: "Kinkakuji Temple", description: "Kinkakuji (金閣寺, Golden Pavilion) is a Zen temple in northern Kyoto whose top two floors are completely covered in gold leaf. Formally known as Rokuonji, the temple was the retirement villa of the shogun Ashikaga Yoshimitsu, and according to his will it became a Zen temple of the Rinzai sect after his death in 1408. Kinkakuji was the inspiration for the similarly named Ginkakuji (Silver Pavilion), built by Yoshimitsu's grandson, Ashikaga Yoshimasa, on the other side of the city a few decades later.", address: "1 Kinkakujicho, Kita, Kyoto, Kyoto Prefecture 603-8361, Japan", image_url: "https://i.redd.it/h7k55cocavrz.jpg"})

Activity.create({country: "Japan", name: "Kinkaku Soft", description: "Not only from all over Japan, a lot of people visit Kinkakuji from all over the world. However, Kinkakuji is located a little outside of central Kyoto. Unlike major tourist sites, Kinkakuji is less crowded. We wanted to welcome those people who visit Kinkakuji with a little fun which you can imagine of Kinkakuji. That is how Kinkaku Soft(soft-served ice cream) was created. The gold leaf used for Kinkaku Soft is a real gold. There are a lot of grade to the gold leaf, but we selected the one with higher content of gold and using the special food grade gold leaf. Also, based on the research on brain wave and emotion, it vitalizes the left brain and distress after eating pure gold. It also states eating pure gold gives you comfortable feeling. Very luxurious experience eating pure gold also gives you a good effect to your heart. Vanilla flavor is with rich raw milk. Matcha flavor is with stone-ground high grade matcha powder. Because of this delicate cream, the color would change if it’s not fresh. Topped with small rice cake ball, sweet azuki beans, and whipped cream, it’s like a parfait on the go. Kinkaku Soft used Japanese traditional crafted paper called washi for the cone sleeve. To get the deep color, we are using the best of kind washi Genryu and put gold and silver leaf and embossed our logo. The craftsman specially made this washi for Kinkaku Soft. Please enjoy this Japanese craftsmanship with your own eyes and feel the luxurious texture.", address:"38-1 Kinugasanishi Goshonouchichō, Kita-ku, Kyōto-shi, Kyōto-fu 603-8377, Japan", image_url: "http://kinkakusoft.com/wp-content/uploads/2016/06/menue-1.jpg"})

Activity.create({country: "Japan", name: "Nishiki Market", description: "Nishiki Market (錦市場, Nishiki Ichiba) is a narrow, five block long shopping street lined by more than one hundred shops and restaurants. Known as Kyoto's Kitchen, this lively retail market specializes in all things food related, like fresh seafood, produce, knives and cookware, and is a great place to find seasonal foods and Kyoto specialties, such as Japanese sweets, pickles, dried seafood and sushi. Nishiki Market has a pleasant but busy atmosphere that is inviting to those who want to explore the variety of culinary delights that Kyoto is famous for. The stores found throughout the market range in size from small narrow stalls to larger two story shops. Most specialize in a particular type of food, and almost everything sold at the market is locally produced and procured. Some of the shops freely give out samples or sell sample dishes and skewers meant to be eaten then and there. There are also a few small restaurants and food stands selling ready-made food. A few are sit-down establishments, although some consist of no more than a couple of stools and a bar. They usually specialize in one type of food, and are often attached to a store of the same specialty.", address: "Nakagyo Ward, Kyoto, Kyoto Prefecture 604-8052", image_url: "https://thecitylane.com/wp-content/uploads/2014/09/DSCF2968.jpg"})

Activity.create({country: "Japan", name: "Nijo-jo Castle", description: "Nijo Castle (二条城, Nijōjō) was built in 1603 as the Kyoto residence of Tokugawa Ieyasu, the first shogun of the Edo Period (1603-1867). His grandson Iemitsu completed the castle's palace buildings 23 years later and further expanded the castle by adding a five story castle keep. After the Tokugawa Shogunate fell in 1867, Nijo Castle was used as an imperial palace for a while before being donated to the city and opened up to the public as a historic site. Its palace buildings are arguably the best surviving examples of castle palace architecture of Japan's feudal era, and the castle was designated a UNESCO world heritage site in 1994.", address: "541 Nijojocho, Nakagyo Ward, Kyoto, Kyoto Prefecture 604-8301, Japan", image_url: "https://www.japanmeetings.org/assets/images/why-japan/unique-venues/pic_nijo_jo_main.jpg"})

Activity.create({country: "Japan", name: "Nadai tonkatsu katsukura", description: "Part of a tonkatsu chain focused on the Kansai area, this is the main store located in Kyoto. The entrance is very narrow, so be mindful you don’t miss it. The tonkatsu here are very light and healthy. On top of that, the umami of the pork is well-preserved and is quite delicious and easily digested. You can add sesame seeds to your own sauce before eating. In addition to pork, chicken, shrimp and other katsu are available, and you can also have it to-go in sandwich form. You can enjoy eating tonkatsu made to your own preferences.", address: "Japan, 〒604-8042 Kyoto Prefecture, Kyoto, Nakagyo Ward, 寺町通四条上ル", image_url: "https://cdn-images-1.medium.com/max/1600/1*eRVdWKVGRlXSfo51k6pGmg.jpeg"})

Activity.create({country: "Japan", name: "Ginkakuji Temple", description: "Ginkakuji (銀閣寺, Silver Pavilion) is a Zen temple along Kyoto's eastern mountains (Higashiyama). In 1482, shogun Ashikaga Yoshimasa built his retirement villa on the grounds of today's temple, modeling it after Kinkakuji (Golden Pavilion), his grandfather's retirement villa at the base of Kyoto's northern mountains (Kitayama). The villa was converted into a Zen temple after Yoshimasa's death in 1490. Today, Ginkakuji consists of the Silver Pavilion, half a dozen other temple buildings, a beautiful moss garden and a unique dry sand garden. It is enjoyed by walking along a circular route around its grounds, from which the gardens and buildings can be viewed.", address: "2 Ginkakujicho, Sakyo Ward, Kyoto, Kyoto Prefecture 606-8402, Japan", image_url: "https://d3bbatwdaufxg9.cloudfront.net/content/1014/5552/5536/01-20140228_Ginkakuji_Mainspot-81.jpg"})

Activity.create({country: "Japan", name: "Heian Shrine", description: "Heian Shrine (平安神宮, Heian Jingū) has a relatively short history, dating back just over a hundred years to 1895. The shrine was built on the occasion of the 1100th anniversary of the capital's foundation in Kyoto and is dedicated to the spirits of the first and last emperors who reigned from the city, Emperor Kammu (737-806) and Emperor Komei (1831-1867). Heian is the former name of Kyoto. A giant torii gate marks the approach to the shrine, around which there are a couple of museums. The actual shrine grounds themselves are very spacious, with a wide open court at the center. The shrine's main buildings are a partial replica of the original Imperial Palace from the Heian Period, built on a somewhat smaller scale than the original.", address: "Okazaki Nishitennocho, Sakyo Ward, Kyoto, Kyoto Prefecture 606-8341, Japan", image_url: "https://letsjapan.files.wordpress.com/2012/06/hj-winter-91_wpb.jpg"})

Activity.create({country: "Japan", name: "Pokemon Center(Kyoto)", description: "The shop, which covers an area of 206.2 square metres (2,219 square feet), will stock all types of Pokémon merchandise, from plush toys to clothing, accessories and stationery. There’ll also be a large number of original goods combining the world of Pokémon with Kyoto-themed elements, making them ideal souvenirs for tourists both from within Japan and abroad. There are currently nine Pokémon Centers around Japan, with locations in Fukuoka, Osaka, Hiroshima, Nagoya, Yokohama, Sendai, Sapporo, Chiba, and Ikebukuro in Tokyo. Each store has their own range of original goods, and for the opening in Kyoto, customers can expect to see a very special type of Pikachu, designed to embody the culture and feel of the historic locale.", address: "Japan, 〒600-8520 Kyōto-fu, Kyōto-shi, Shimogyō-ku, Shinchō, 四条通河原町西入真町52 京都髙島屋 5F", image_url: "https://i.ytimg.com/vi/nlBhsgdAYTM/maxresdefault.jpg"})

Activity.create({country: "Japan", name: "Taishoken", description: "Taishoken is one of the most famous ramen shops in Tokyo. Its owner, Kazuo Yamagishi, is said to be the inventor of tsukemen. While traditional ramen is a soup consisting of noodles, broth, and toppings all served together in a bowl, tsukemen is noodles and soup served separately. The soup that comes with tsukemen is usually a little more potent in flavor than typical ramen broth, and is meant to be used as a dipping sauce for the noodles rather than to drink. While tsukemen is now common food in Japan, Taishoken is considered to be the original.", address: "4-28-3 Higashi Ikebukuro, Toshima-ku, Tokyo", image_url: "https://farm8.staticflickr.com/7624/17000074596_5b23c8e0ee_c.jpg"})

Activity.create({country: "Japan", name: "Soba - Sobanomi Yoshimura", description: "Sobanomi Yoshimura is famous for their good selection of sake, and freshly made, proper soba noodles. The restaurant is located on Gojo-dori Street, close to subway Gojo station. The machiya town house style of the place stands out prominently among the modern office buildings of Gojo-dori Street. This restaurant chain has four restaurants in Kyoto, the main one in Arashiyama, one close to Kiyomizu-dera Temple, one in Kitayama, and then this restaurant on Gojo-dori Street. This restaurant is famous home and abroad, and many tourists keep coming to this restaurant, to taste the great soba and Kyoto-like atmosphere. During peak times there is often a line in front of the restaurant.", address: "420 松屋町 Shimogyo Ward, Kyoto, Kyoto Prefecture 600-8105, Japan", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/06/fc/44/cf/caption.jpg"})

Activity.create({country: "Japan", name: "Arashiyama Bamboo Forest", description: "The Arashiyama Bamboo Grove is one of Kyoto’s top sights and for good reason: standing amid these soaring stalks of bamboo is like being in another world. If you’ve been planning a trip to Kyoto, you’ve probably seen pictures of the Arashiyama Bamboo Grove – along with the torii tunnels of Fushimi-Inari-Taisha Shrine and Kinkaku-ji Temple, it’s one of the most photographed sights in the city. But no picture can capture the feeling of standing in the midst of this sprawling bamboo grove – the whole thing has a palpable sense of otherness that is quite unlike that of any normal forest we know of.", address: "Arashiyama Genrokuzancho, Ukyō-ku, Kyoto, Kyoto Prefecture 616-0007, Japan", image_url: "https://i.redd.it/atxstyml9yt11.jpg"})

Activity.create({country: "Japan", name: "Ryoan-Ji Temple", description: "Ryoanji Temple (龍安寺, Ryōanji) is the site of Japan's most famous rock garden, which attracts hundreds of visitors every day. Originally an aristocrat's villa during the Heian Period, the site was converted into a Zen temple in 1450 and belongs to the Myoshinji school of the Rinzai sect of Zen Buddhism, whose head temple stands just a kilometer to the south. As for the history of Ryoanji's famous rock garden, the facts are less certain. The garden's date of construction is unknown and there are a number of speculations regarding its designer. The garden consists of a rectangular plot of pebbles surrounded by low earthen walls, with 15 rocks laid out in small groups on patches of moss. An interesting feature of the garden's design is that from any vantage point at least one of the rocks is always hidden from the viewer.", address: "13 Ryoanji Goryonoshitacho, Ukyō-ku, Kyoto, Kyoto Prefecture 616-8001, Japan", image_url: "https://www.travelcaffeine.com/wp-content/uploads/2018/03/ryoanji-temple-kyoto-japan-040.jpg"})

Activity.create({country: "Japan", name: "Toei Kyoto Studio Park", description: "Toei Kyoto Studio Park is the only theme park in Japan where you can observe the filming of period dramas (jidaigeki films). Here you can walk freely around the Toei Kyoto Studio film set. This set depicts a street from the Edo period, and is used to shoot more than 200 films per year. Enjoy the atmosphere of ancient Japan by taking in a ninja show maybe even dressing up as a geisha or samurai. You will find all kinds of entertainment for both the young and the old, in this world of imagination and creation.", address: "10 Uzumasa Higashihachiokachō, Ukyō-ku, Kyōto-shi, Kyōto-fu 616-8161, Japan", image_url: "http://buffalotrip.com/image/data/2016/Kyoto-2/Experience-the-Edo-Period-at-Toei-Kyoto-Studio-Park-Toei-Uzumasa-Eigamura/show-Experience-the-Edo-Period-at-Toei-Eigamura-kyoto-travel-guide.jpg"})

Activity.create({country: "Japan", name: "Mt. Fuji", description: "Mount Fuji (富士山, Fujisan) is with 3776 meters Japan's highest mountain. It is not surprising that the nearly perfectly shaped volcano has been worshiped as a sacred mountain and experienced big popularity among artists and common people throughout the centuries. Mount Fuji is an active volcano, which most recently erupted in 1707. It stands on the border between Yamanashi and Shizuoka Prefectures and can be seen from Tokyo and Yokohama on clear days.Another easy way to view Mount Fuji is from the train on a trip between Tokyo and Osaka. If you take the shinkansen from Tokyo in direction of Nagoya, Kyoto and Osaka, the best view of the mountain can be enjoyed from around Shin-Fuji Station on the right hand side of the train, about 40-45 minutes into the journey.", address: "Kitayama, Fujinomiya, Shizuoka Prefecture 418-0112, Japan", image_url: "https://i.imgur.com/XUXe9Wj.jpg"})

Activity.create({country: "Japan", name: "Maple Corrido", description: "One of the most popular spots to see red leaves in Japan is the Maples Corridor or Momiji Kairou at Lake Kawaguchi. Momiji means red leaves and a Momiji Matsuri festival is held every year from the end of October to mid November with road stalls and romantic night illumination, so it is a popular destination during November for people to see both Mount Fuji and red leaves.", address: "Japan, 〒401-0304 Yamanashi Prefecture, Minamitsuru District, Fujikawaguchiko, 富士河口湖町河口", image_url: "https://previews.123rf.com/images/blanscape/blanscape1602/blanscape160200098/54233748-maple-corridor-near-by-lake-kawaguchiko-japan.jpg"})

Activity.create({country: "Japan", name: "Chureito Pagoda", description: "The Chureito Pagoda (忠霊塔, Chūreitō) is a five storied pagoda on the mountainside overlooking Fujiyoshida City and Mount Fuji off in the distance. The pagoda is part of the Arakura Sengen Shrine and was built as a peace memorial in 1963 nearly 400 steps up the mountain from the shrine's main buildings. The location offers spectacular views of Mount Fuji in combination with the pagoda, especially during the cherry blossom season in mid April when there are hundreds of trees in bloom and during the autumn color season which usually takes place in the first half of November. The spot is particularly popular among photographers as it allows for some wonderfully stereotypical shots of Japan.", address: "3360-1 Arakura, Fujiyoshida, Yamanashi Prefecture 403-0011, Japan", image_url: "https://www.jrailpass.com/blog/wp-content/uploads/2019/02/chureito-pagoda.jpg"})

Activity.create({country: "Japan", name: "Kuromon Market", description: "Until the end of the Meiji Era, the Kuromon Ichiba Market used to be called Emmeiji Market, because there was once a large temple called Emmeiji nearby. Since there used to be a black gate northeast of this temple, the marketplace later came to be calledKuromon Ichiba Market(Black Gate Market). The market has a total length of close to 600 meters with 170 shops, the vast majority of which specialize in the freshest and best quality meat, vegetables, eggs and other ingredients from around the country and abroad. Although well over half of total sales are for the business (professional chef) market, Kuromon Ichiba caters also to the general public. For more than 170 years, everyone from restaurant chefs to housewives have come here, drawn by the taste, freshness and variety of its products.", address: "2 Chome-3-2 Nipponbashi, Chūō-ku, Ōsaka-shi, Ōsaka-fu 542-0073, Japan", image_url: "https://external-preview.redd.it/z_ElusEeJOdHjym0gdKFLCVno1wCZ74kQxY6QZmnfxA.jpg?auto=webp&s=c7f76bb79e8109543046704fd636806aafbcdd5e"})

Activity.create({country: "Japan", name: "Dotonbori Market", description: "Osaka's hotspot for tourists and revelers alike, Dotonbori is filled with towering neon signs, clubs, bars, and restaurants serving up local specialties. Come here for a stimulating and essential slice of Osaka nightlife. The towering walls of neon that cover the buildings of Dotonbori are a testament to Japan's bright optimism during a time when neon reigned supreme as a new and promising technology. The entire area is preserved in this retro-futurist ambiance, perfect for tourists looking for a stereotypical Japanese metropolitan vibe.", address: "Chuo, Osaka, Osaka Prefecture 542-0071", image_url: "https://i.imgur.com/XDe7WW5.jpg"})

Activity.create({country: "Japan", name: "Osaka Castle", description: "The construction of Osaka Castle (大阪城, Ōsakajō) started in 1583 on the former site of the Ishiyama Honganji Temple, which had been destroyed by Oda Nobunaga thirteen years earlier. Toyotomi Hideyoshi intended the castle to become the center of a new, unified Japan under Toyotomi rule. It was the largest castle at the time. However, a few years after Hideyoshi's death, Tokugawa troops attacked and destroyed the castle and terminated the Toyotomi lineage in 1615. Osaka Castle was rebuilt by Tokugawa Hidetada in the 1620s, but its main castle tower was struck by lightening in 1665 and burnt down. It was not until 1931 that the present ferro-concrete reconstruction of the castle tower was built. During the war it miraculously survived the city wide air raids. Major repair works gave the castle new glamor in 1997. The castle tower is now entirely modern on the inside and even features an elevator for easier accessibility. It houses an informative museum about the castle's history and Toyotomi Hideyoshi.", address: "1-1 Ōsakajō, Chūō-ku, Ōsaka-shi, Ōsaka-fu 540-0002, Japan", image_url: "https://i.redd.it/rl3uv7rr9sn11.jpg"})

Activity.create({country: "Japan", name: "Pokemon Center(Osaka)", description: "Pokemon Center Osaka is located on the 13th floor of Daimaru Umeda department store, next to Osaka Station. Not only is the location itself superb, there is also a large Uniqlo on the same floor as the Pokemon Center, so parents bringing their children to play can shop instead of just waiting for their kids to tire out. The upper floor is also packed with restaurants so grownups can enjoy a coffee break while their kids are engrossed in games downstairs. The Pokemon Center is an open space without walls and has a good view of the Uniqlo store – an effective layout for parents who want to check on their kids while they shop.", address: "Japan, 〒530-8202 Ōsaka-fu, Ōsaka-shi, Kita-ku, Umeda, 3 Chome−3−1-1 大丸梅田店13F", image_url: "https://www.justgola.com/media/a/00/01/7758_og_1.jpeg"})

Activity.create({country: "Japan", name: "Ueshima", description: "If you are foodie, you probably know that Osaka is the place to fulfill your needs. We took a weekend trip to Osaka (we live in Tokyo) and decided to go to one of hidden Kushikatsu restaurants called Ueshima. These kind of Japanese restaurants could be a bit intimidating for tourists and even for some locals so I will show you what it's like and what you should expect.", address: "大阪府大阪市北区芝田1-1-3阪急三番街南館B1F, 1 Chome-1 Shibata, Kita-ku, Ōsaka-shi, Ōsaka-fu 530-0012, Japan", image_url: "https://static1.squarespace.com/static/5856239415d5db5111f74d82/t/5981d5dc37c5816dcb731e14/1501681155321/osaka+restaurants?format=750w"})

Activity.create({country: "Japan", name: "Kaiten Sushi", description: "First of all, how does rotating sushi work? When you sit down, you can grab a pen and the list of sushi. Put down your seat number (it should be right in front of you) at the top of the list and pick your selections of what you want (if you want it extra fresh or if the item you want is not on the rotating belt). Or you can make your selections from the belt and pick whatever you want. The pricing depends on what plate the food is on. The wall will show you each pricing and it ranges from 0.99-$6.00. Keep your eyes out for the chalkboard specials because they have daily specials that are stealer prices!", address: "3 Chome-3-9-1 Toyosaki, Kita-ku, Ōsaka-shi, Ōsaka-fu 531-0072, Japan", image_url: "https://uds.gnst.jp/rest/img/2wxz53540000/s_003c.jpg?dt=1470112065"})

Activity.create({country: "Japan", name: "Hep Five", description: "One of Umeda’s best known landmarks, HEP FIVE is essentially a shopping mall that just happens to have a huge red Ferris wheel attached to its roof. HEP is an acronym for Hankyu Entertainment Park, and although the bulk of the building is devoted to clothing stores, there are also dining facilities and amusement zones on the upper floors. Let’s take a look at each of the facilities in turn.", address: "5-15 Kakudacho, Kita, Osaka, Osaka Prefecture 530-0017, Japan", image_url: "https://www.hepfive.jp/language/images/top/lgg_img_info.jpg"})

Activity.create({country: "Japan", name: "T's Tan Tan", description: "There is decent vegan ramen to be had in Tokyo... but it's a little tricky to find. T's Tan Tan is located INSIDE the turnstiles at Tokyo Station. That's right, you need to either be traveling on the JR train system already, or you need to buy a platform ticket (¥130 nyuujouken gets you past the ticket gates but not onto a train) to access the food and shopping area inside of the station. T's Tan Tan offers several types of ramen, including white (sesame, bean sprouts, and thick green onion in a spicy broth: this one is my favorite, it really clears out your sinuses!), green (ramen piled high with fresh greens and includes some kabocha squash), shoyu (soy-sauce based broth), red (tomato base) and more. A bowl of ramen will set you back about 850 yen. They also have salads and curry rice, and can provide a big helping for a few hundred yen more. Everything is vegan, as the pictures and text on the walls proudly proclaim. An English menu is available for those who want it, and the menu is illustrated so it's easy to pick and point. The staff also speaks a little English (and some speak Taiwanese). Beer and soft drinks are available.", address: "Japan, 〒100-0005 Tokyo, Chiyoda, Marunouchi, 1 Chome−9−1 JR東京駅（改札内）KeiyoStreet", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/0c/58/d9/c6/t-s-tantan-tokyostation.jpg"})

Activity.create({country: "Japan", name: "Soranoiro", description: "The Tokyo Station shop is Soranoiro's third outpost. With four in Tokyo and one in Nagoya, each shop has a different menu. At Soranoiro NIPPON, the shoyu ramen here is reputedly excellent, and they have an Okinawan-style bowl with a goodly chunk of stewed pork belly. (Who doesn’t like stewed pork belly?) But one thing all of the Soranoiro shops have in common is using, to put it mildly, a fuckton of vegetables in their ramen bowls. Many of the options are vegetarian, even vegan, even gluten-free.", address: "Japan, 〒100-0005 Tokyo, Chiyoda, Marunouchi, 1 Chome−9−1 JR東京駅（改札内）KeiyoStreet", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/0e/fa/02/75/photo0jpg.jpg"})

Activity.create({country: "Japan", name: "Mandarake Complex", description: "Are you into secondhand manga or vintage games? Whether you’re into collectible figurines and cards or fan-drawn manga, there’s something for everyone at the 8-floor Mandarake Complex in Akihabara. If nothing else, it’s worth going just to gawk at the goods on display. Collecting manga can get expensive quickly. But if you're buying secondhand, your comic book budget will go that much further. To stock up on manga during your trip to Tokyo, head over to Mandarake in Akihabara, a secondhand bookstore carrying - you guessed it - manga.", address: "３丁目-12-11 Sotokanda, Chiyoda-ku, Tōkyō-to 101-0021, Japan", image_url: "https://thecupandtheroad.files.wordpress.com/2016/07/mandarake-nakano-1090643.jpg"})

Activity.create({country: "Japan", name: "Imperial Palace", description: "The current Imperial Palace (皇居, Kōkyo) is located on the former site of Edo Castle, a large park area surrounded by moats and massive stone walls in the center of Tokyo, a short walk from Tokyo Station. It is the residence of Japan's Imperial Family. From Kokyo Gaien, the large plaza in front of the Imperial Palace, visitors can view the Nijubashi, two bridges that form an entrance to the inner palace grounds. The stone bridge in front is called Meganebashi (Eyeglass Bridge) for its looks. The bridge in the back was formerly a wooden bridge with two levels, from which the name Nijubashi (Double Bridge) is derived.", address: "1-1 Chiyoda, Chiyoda-ku, Tōkyō-to 100-8111, Japan", image_url: "https://www.jnto.go.jp/ph/spot-activity/wp-content/uploads/sites/2/2018/10/Imperial-Palace-01.jpg"})

Activity.create({country: "Japan", name: "Tsukiji Fish Market", description: "Great place to visit if you love to eat fresh fish or sushi. Choose from a variety of welcoming shops and restaurants. Fish is also sold in this market but be sure to arrive early as the best fish tends to sell out early in the morning.", address: "5 Chome-2-1 Tsukiji, Chūō, Tokyo 104-0045, Japan", image_url: "http://i.imgur.com/36Sn9qR.jpg"})

Activity.create({country: "Japan", name: "Tokyo Sushi Academy Tsukiji", description: "The Tokyo Sushi Academy offers a 90-minute intensive course in making sushi. Their skilled professional sushi chefs deliver high-quality lessons that capture the very essence of Edo-mae sushi, teaching you how to make sushi with the utmost care and attention to detail.", address: "4 Chome-7-5 Tsukiji, 中央区築地 Tōkyō-to 104-0045, Japan", image_url: "https://image.cookly.me/tr:h-214,w-380,pr-true,rt-auto/images/Tokyo-Sushi-Academy-4.jpg"})

Activity.create({country: "Japan", name: "Kiyomizu Temple", description: "Kiyomizudera (清水寺, literally Pure Water Temple) is one of the most celebrated temples of Japan. It was founded in 780 on the site of the Otowa Waterfall in the wooded hills east of Kyoto, and derives its name from the fall's pure waters. The temple was originally associated with the Hosso sect, one of the oldest schools within Japanese Buddhism, but formed its own Kita Hosso sect in 1965. In 1994, the temple was added to the list of UNESCO world heritage sites. Kiyomizudera is best known for its wooden stage that juts out from its main hall, 13 meters above the hillside below. The stage affords visitors a nice view of the numerous cherry and maple trees below that erupt in a sea of color in spring and fall, as well as of the city of Kyoto in the distance. The main hall, which together with the stage was built without the use of nails, houses the temple's primary object of worship, a small statue of the eleven faced, thousand armed Kannon.", address: "294 Kiyomizu 1-chōme, Higashiyama-ku, Kyōto-shi, Kyōto-fu 605-0862, Japan", image_url: "https://i.redd.it/ucugid2x8hm21.jpg"})

Activity.create({country: "Japan", name: "Wagyumafia The Cutlet Sandwich Nakameguro", description: "WAGYUMAFIA was founded by self-taught chef-turned-wagyu experts Hisato Hamada and entrepreneur Takafumi Horie. Originally in the beef export business, the brand was created following a series of private dinner pop-ups around the theme of wagyu. The duo later launched their first members-only restaurant, The WAGYUMAFIA Progressive Kaiseki, in Tokyo in 2016. With a mission to educate consumers, restaurateurs and suppliers on authentic Japanese wagyu beef, the WAGYUMAFIA brand is a platform that showcases the dedicated work of Japan’s wagyu farmers which is deeply rooted in history and tradition. Driven by a collaborative spirit, WAGYUMAFIA has embarked on a 50-city world tour, bringing knowledge and expertise into a series of exciting and high-profile chef collaborations, including Spain’s 3-Michelin star Azurmendi, London’s Soho House, Fortnum & Mason and Spago in Los Angeles.", address: "Japan, 〒153-0051 Tokyo, Meguro, Kamimeguro, １ 丁目 ２６−１−１０８", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/14/55/39/60/kobe-chateaubriand.jpg"})

Activity.create({country: "Japan", name: "Tokyo Tower", description: "Standing 333 meters high in the center of Tokyo, Tokyo Tower (東京タワー) is the world's tallest, self-supported steel tower and 13 meters taller than its model, the Eiffel Tower. A symbol of Japan's post-war rebirth as a major economic power, Tokyo Tower was the country's tallest structure from its completion in 1958 until 2012 when it was surpassed by the Tokyo Skytree. In addition to being a popular tourist spot, Tokyo Tower serves as a broadcast antenna. The tower's main deck at 150 meters is reached via elevator or a 600-step staircase (both paid). Thanks to the tower's central location, the observatory offers an interesting view of the city despite being only at a relatively moderate height. There are also some lookdown windows in the floor to stand on, a souvenir shop and a cafe where visitors can enjoy refreshments. A second set of elevators connect the main deck to the 250 meter high top deck, from where you can get a bird's eye view of Tokyo from high above the surrounding buildings. It is the third highest observation deck in Tokyo (after the two decks at the Tokyo Skytree). When visibility is good, visitors can see the Tokyo Skytree and Mount Fuji in the distance. Directly below the tower stands the Foot Town building, which houses a variety of souvenir shops, cafes, restaurants and the One Piece Tower, an indoor amusement park. Opened on the 15th anniversary of the popular manga in 2015, the park offers a variety of shows, games and other attractions that feature characters from the series.", address: "4 Chome-2-8 Shibakōen, Minato-ku, Tōkyō-to 105-0011, Japan", image_url: "https://i.redd.it/94mqy1l95oe21.jpg"})

Activity.create({country: "Japan", name: "Tokyo Whiskey Library", description: "Anyone not very familiar with but willing to learn more about whisky best make straight for this Aoyama hideout. Pass the church on the ground floor of the elegant Santa Chiara complex and climb the stairs to find the door to Whisky Library, distinguished by – of course – its bookcases. And as you’d expect, these shelves are filled not with dusty old tomes but with a stunning collection of more than 1,200 different distilled spirits, sourced from all of the world’s major whisky (and whiskey) regions. Aiming to help newbies learn more about the overwhelming variety of fine malts, this bar has none of that ‘connoisseurs only’ attitude sometimes evident at other Tokyo whisky bars, and provides a simple menu of standard options to get your sipping started. The 82 seats include sofas, stools and seating in private rooms, encouraging you to admire your drink from a variety of angles and in different lighting conditions – you’ll feel like you can discover something new even if you order the same tipple twice.", address: "Japan, 〒107-0062 Tokyo, Minato, Minamiaoyama, ５丁目5−24 南青山サンタキアラ教会", image_url: "http://www.tokyo-whisky-library.com/en/assets/images/main00.png"})

Activity.create({country: "Japan", name: "Ghibli Museum",description: "When you walk along Kichijoji Avenue, in the shade of the tall green trees of Mitaka's Inokashira Park, you come upon a colorful building. Standing in front of a sign that says Ghibli Museum, Mitaka, a very large Totoro welcomes you at the entrance. When you look through the portholes, soot-black Dust Bunnies are there as well. But this is not the real entrance. Totoro shows you where the real entrance is. Open the door and welcome to wonderland! Every window and lamp is lovingly hand-crafted with beautiful and colorful stained glass using Ghibli characters, pretty plants and flowers, and forest animals. When the sun is shining, the vivid colors of the glass are reflected in splashes of colored light on the stone floors.", address: "1 Chome-1-83 Shimorenjaku, Mitaka-shi, Tōkyō-to 181-0013, Japan", image_url: "https://en.compathy.net/magazine/wp-content/uploads/2016/11/74778993_YBRtrKtjNufe-wcdTq-S1Q_X1GW-4KlxOkojZzRta10.jpg"})

Activity.create({country: "Japan", name: "Nakano Broadway", description: "Nakano Broadway (中野ブロードウェイ) is a shopping complex in Tokyo famous for its many stores selling anime items and idol goods, inlcuding more than a dozen small Mandarake stores, which specialize in manga and anime related collectibles. The shopping complex is a short walk from Nakano Station, which is five minute train ride from Shinjuku via the JR Chuo Line. There are four levels of shopping at the Nakano Broadway. The second and third levels are where the many anime and idol related shops are located. Here, shoppers can find manga, magazines, collectors' items, animation character figurines, idol merchandise, game consoles, video games, animation/idol related CDs, as well as little souvenirs to take home, such as idol playing cards or key chains. The ground level of the Nakano Broadway has shops selling clothes, shoes, tidbits and second hand goods. The basement level is a marketplace, where the locals shop for their groceries. Products on sale range from fruits and vegetables to meat and seafood. Leading to the Nakano Broadway from Nakano Station is the Nakano Sunmall, a 225 meter long, covered shopping street with a wide variety of shops, including food joints, cafes, watch dealers, jewelers, fashion boutiques, pharmacies, game centers, book stores and others. On the side streets branching off from the shopping street are food alleys with various restaurants, including many izakaya (Japanese style pub/eatery), that serve all different kinds of food. Here one can experience the atmosphere of the bustling food crowd while taking a break from the shopping.", address: "5 Chome-52 Nakano, Tokyo 164-0001, Japan", image_url: "https://i.redd.it/qy53dsct1nv01.jpg"})

Activity.create({country: "Japan", name: "Nanaya Aoyama", description: "Shizuoka-based matcha sweets purveyors Nanaya, famed for their Premium No. 7 gelato that's been certified as the ice cream with the world's highest matcha content, have hardly been very active in appealing to Tokyoites: until August 2016, their only outpost in the capital was a simple counter inside Asakusa tea shop Suzukien. But now they've finally taken the next step and opened their very own shop in Aoyama, near Aoyama Gakuin University. In addition to the fabled No. 7, Nanaya Aoyama stocks six other varieties of matcha ice cream ranked in order of richness (just like at the Suzukien shop), as well as matcha daifuku sweets, matcha cookies and even matcha chocolate. If green tea is your cup of tea, so to speak, this one should not be missed.", address: "Japan, 〒150-0002 Tōkyō-to, Shibuya-ku, Shibuya, 2 Chome−7−12", image_url: "http://amu-zen.com/wp-content/uploads/sites/4/2016/08/f9c847f8166aa127f643ebf61068eb1f.jpg"})

Activity.create({country: "Japan", name: "Harajuku", description: "Harajuku (原宿) refers to the area around Tokyo's Harajuku Station, which is between Shinjuku and Shibuya on the Yamanote Line. It is the center of Japan's most extreme teenage cultures and fashion styles, but also offers shopping for adults and some historic sights. The focal point of Harajuku's teenage culture is Takeshita Dori (Takeshita Street) and its side streets, which are lined by many trendy shops, fashion boutiques, used clothes stores, crepe stands and fast food outlets geared towards the fashion and trend conscious teens.", address: "Shibuya, Tokyo 150-0001", image_url: "https://c-lj.gnst.jp/public/article/detail/a/00/00/a0000115/img/basic/a0000115_main.jpg?20180919112119"})

Activity.create({country: "Japan", name: "Abura Soba", description: "Abura Soba originated from the Kitatama district of Tokyo in the early 1950s. There are a few popular chains in the Kanto area that specialize in this type of noodles, and its popularity continues to grow. Abura soba is relatively easy to make as it doesn’t require a soup-base that takes half a day to prepare, and it costs only roughly 150yen per bowl to make as oppose to the 300yen for typical ramen. Therefore, more and more ramen shops are offering abura soba as an alternative menu item. Thanks to its cheap cost, it is also very common that you can get oomori (extra noodles) for no extra cost. To simply describe abura soba, it is a bowl of thick noodles with a special shouyu (soy sauce) and pork grease sauce placed at the bottom of the bowl. Typical toppings include: green onion, boiled bamboo shoot, seaweed, minced garlic and chashu pork, and the standard condiments of vinegar and chilli oil. Other common but optional additions include: sesame, black pepper, spicy preserved vegetables, more minced garlic, red ginger, boiled egg, raw egg, cheese, mayonnaise and spicy condiments like ichi-mi (chilli pepper powder) or even Toubanjan (Chinese spicy bean paste).", address: "3 Chome-18-10 Shibuya, Shibuya-ku, Tōkyō-to 150-0002, Japan", image_url: "https://1.bp.blogspot.com/-KeAcq5uqzas/VQW0t5nimfI/AAAAAAAA3_s/_1I07PDXvZM/s1600/ABURA%2B(9%2Bof%2B9).jpg"})

Activity.create({country: "Japan", name: "Togoshi Ginza", description: "Next to Togoshi-Ginza Station is Togoshi Ginza Shopping District, a long strip lined with hit restaurants and shops. Don't be surprised if you bump into TV celebrities and cameramen lugging around film equipment as the street is often featured on food-related programs and in popular foodie magazines. As you make your way down the strip, don't miss the chance to sample some of Tokyo's best snacks. Here you can buy everything from rarities like oden croquettes to comfort foods like curry pan (savory curry-filled bread rolls), and cute cat-shaped doughnuts from the popular Floresta doughnut store", address: "2 Chome-1-6 Togoshi, Shinagawa-ku, Tōkyō-to 142-0041, Japan", image_url: "https://media.timeout.com/images/103394803/630/472/image.jpg"})

Activity.create({country: "Japan", name: "T.Y. Harbor", description: "Brewery restaurant residing right next to the brewery itself. A Tennoz area landmark overlooking the canal and the waterfront lounge floating in front. The restaurant located right next to its brewery. There are over 350 seats in the dining area, starting with the our craft beer bar, private room, 2nd floor seating and terrace seating overlooking the water and Tokyo’s only floating lounge River Lounge. T.Y. Harbor stands as a landmark for the Tennoz area where you can enjoy your dining experience to its fullest.", address: "２丁目-1-3 Higashishinagawa, Shinagawa, Tokyo 140-0002, Japan", image_url: "https://media.timeout.com/images/103896127/630/472/image.jpg"})

Activity.create({country: "Japan", name: "VR Zone Shinjuku", description: "Located in Kabukicho near the infamous Robot Restaurant, this futuristic wonderland is a sight to behold. If you’re a gamer or otherwise interested in checking out some of the cutting edge virtual reality, I highly suggest budgeting some time for a visit. One-day tickets for VR Zone Shinjuku can be purchased for 4,400 yen. You can reserve tickets on either the VR Zne website or via a special app. The website also provides additional information available in both English and Japanese. Visitors basically pay for the opportunity to sample up to four attractions. You’ll receive a red, yellow, blue, and green ticket which can be used on one of the following experiences. Since the tickets are divided by genre, this unfortunately means you’ll need to make some hard decisions; choose wisely! In addition to the four-color tickets, there are also other experiences that you can partake in such as: a rock climbing attraction, a panic room, and a Niagara waterfall drop. You can pay for these on site or sacrifice one of your colored tickets but I would recommend you not do so. The added attractions only cost an additional 1,000 yen; it’s not like you can just go get more of the red, yellow, blue, or green tickets.", address: "1 Chome-29-1 Kabukicho, Shinjuku, Tokyo 160-0021, Japan", image_url: "https://cnet2.cbsistatic.com/img/EHE_ND_KLDtphBq0QXzIPIiQI5I=/1600x900/2017/10/20/e8f232cc-25eb-4fa8-a11f-e4e1941fed8d/vr-zone-shinjuku-007.jpg"})

Activity.create({country: "Japan", name: "Shinjuku Gyoen National Garden", description: "Shinjuku Gyoen (新宿御苑) is one of Tokyo's largest and most popular parks. Located just a short walk from Shinjuku Station, the paid park's spacious lawns, meandering walking paths and tranquil scenery provide a relaxing escape from the busy urban center around it. In spring Shinjuku Gyoen becomes one of the best places in the city to see cherry blossoms. Shinjuku Gyoen originated during the Edo Period (1603-1867) as a feudal lord's Tokyo residence. Later it was converted into a botanical garden before being transferred to the Imperial Family in 1903 who used used it for recreation and the entertainment of guests. The park was almost completely destroyed during World War II, but was eventually rebuilt and reopened in 1949 as a public park.", address: "11 Naitomachi, Shinjuku, Tokyo 160-0014, Japan", image_url: "https://i.redd.it/s5fqnh894qn01.jpg"})

Activity.create({country: "Japan", name: "Golden Gai", description: "One of those not-so-secret secret spots, Golden Gai is a collection of mismatched, tumbledown bars lining alleyways in a darkened corner of Shinjuku. While surrounding areas have been developed and look like any other part of Tokyo, Golden Gai retains the post-war charm of scruffiness often lost in the shiny modern metropolis we are more familiar with. Frequented by celebrities and home to myriad small bars and restaurants, each night is an adventure into the unknown and unexpected.", address: "１丁目-1 Kabukichō, Shinjuku-ku, Tōkyō-to 160-0021, Japan", image_url: "https://i.redd.it/37kp1h0dloy01.jpg"})

Activity.create({country: "Japan", name: "Pokemon Center(Tokyo)", description: "As some may know, the biggest Pokémon Center in all of Japan has opened this spring in the Takashimaya department store in Nihonbashi, a very Japanese neighborhood and historical center of Tokyo. The enormous Pokémon Center DX’s location is very convenient with it being located just a short walk from Tokyo station. Even better, it also holds nearly any Pokémon item you can imagine and uses some cutting-edge technology that everyone can enjoy! Pokémon is inarguably one of the most followed and renowned series in Japan—and the world! With fans in many age groups, this makes the Pokémon Center DX a great stop for almost everyone.", address: "Japan, 〒131-0045 Tōkyō-to, Sumida-ku, Oshiage, 1 Chome−1−2 東京スカイツリータウン・ソラマチイーストヤード", image_url: "https://i.ytimg.com/vi/psT1VQ588Yc/maxresdefault.jpg"})

Activity.create({country: "Japan", name: "Tokyo Skytree", description: "The Tokyo Skytree (東京スカイツリー) is a television broadcasting tower and landmark of Tokyo. It is the centerpiece of the Tokyo Skytree Town in the Sumida City Ward, not far away from Asakusa. With a height of 634 meters (634 can be read as Musashi, a historic name of the Tokyo Region), it is the tallest structure in Japan and the second tallest in the world at the time of its completion. A large shopping complex with aquarium is located at its base. The highlight of the Tokyo Skytree is its two observation decks which offer spectacular views out over Tokyo. The two enclosed decks are located at heights of 350 and 450 meters respectively, making them the highest observation decks in Japan and some of the highest in the world.", address: "1 Chome-1-2 Oshiage, Sumida-ku, Tōkyō-to 131-0045, Japan", image_url: "https://i.redd.it/wugk91x4k1k01.jpg"})

Activity.create({country: "Japan", name: "Akihabara", description: "Akihabara (秋葉原), also called Akiba after a former local shrine, is a district in central Tokyo that is famous for its many electronics shops. In more recent years, Akihabara has gained recognition as the center of Japan's otaku (diehard fan) culture, and many shops and establishments devoted to anime and manga are now dispersed among the electronic stores in the district. On Sundays, Chuo Dori, the main street through the district, is closed to car traffic from 13:00 to 18:00 (until 17:00 from October through March). The character of Akihabara has constantly changed over the decades and continues to do so. In the last decade Akihabara has emerged as a center of Japanese otaku and anime culture, and dozens of stores specializing in anime, manga, retro video games, figurines, card games and other collectibles have filled the spaces between the electronics retailers. In addition to shops, various other animation-related establishments have become popular in the area, particularly maid cafes where waitresses dress up and act like maids or anime characters, and manga cafes (manga kissa), a type of internet cafe where customers can read comics and watch DVDs in addition to having access to the internet.", address: "秋葉原 Taitō, Tokyo 110-0006", image_url: "https://i.redd.it/xe9dqjlb64l21.jpg"})

Activity.create({country: "Japan", name: "Tempura Tendon Tenya Asakusa", description: "In order to make the taste of safety and security at a low price, Tenya carefully selects the ingredients, and has established a unique route network from processing to supply. Powder and oil are lives for tempura. Since its establishment, tempura flour has been jointly developed with Nisshin Seifun, Nisshin Foods. The oil is also custom-made to Nisshin oillio from the beginning of the company, and it uses healthy vegetable oil to lighten the flavor and crunchy feeling and the deliciousness of the ingredients, and can not get bored with anyone, repeating the device you enjoy without taste . The Oat fryer (tempura automatic frying machine) also has an environmentally friendly design with almost no waste oil.", address: "Japan, 〒111-0032 Tōkyō-to, Taitō-ku, Asakusa, 1 Chome−9−1 国立ビル", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/0d/88/3d/d6/photo4jpg.jpg"})

Activity.create({country: "Japan", name: "Tokyo National Museum", description: "The Tokyo National Museum (東京国立博物館, Tōkyō Kokuritsu Hakubutsukan) is the oldest and largest of Japan's top-level national museums, which also include the Kyoto National Museum, the Nara National Museum and the Kyushu National Museum. It was originally established in 1972 at Yushima Seido Shrine and moved to its current location in Ueno Park a few years later. The Tokyo National Museum features one of the largest and best collections of art and archeological artifacts in Japan, made up of over 110,000 individual items including nearly a hundred national treasures. At any one time, about 4000 different items from the permanent museum collection are on display. In addition, visiting temporary exhibitions are also held regularly. Good English information and audio guides are available.", address: "13-9 Uenokōen, Taitō-ku, Tōkyō-to 110-8712, Japan", image_url: "https://lonelyplanetimages.imgix.net/a/g/hi/t/d9960974f6e911075de951b22a332fbe-tokyo-national-museum.jpg"})

Activity.create({country: "Japan", name: "Sensoji Temple", description: "Sensoji (浅草寺, Sensōji, also known as Asakusa Kannon Temple) is a Buddhist temple located in Asakusa. It is one of Tokyo's most colorful and popular temples. The legend says that in the year 628, two brothers fished a statue of Kannon, the goddess of mercy, out of the Sumida River, and even though they put the statue back into the river, it always returned to them. Consequently, Sensoji was built nearby for the goddess of Kannon. The temple was completed in 645, making it Tokyo's oldest temple. When approaching the temple, visitors first enter through the Kaminarimon (Thunder Gate), the outer gate of Sensoji Temple and the symbol of Asakusa and the entire city of Tokyo. A shopping street of over 200 meters, called Nakamise, leads from the outer gate to the temple's second gate, the Hozomon. Alongside typical Japanese souvenirs such as yukata and folding fans, various traditional local snacks from the Asakusa area are sold along the Nakamise. The shopping street has a history of several centuries. Beyond the Hozomon Gate stands the temple's main hall and a five storied pagoda. Destroyed in the war, the buildings are relatively recent reconstructions. The Asakusa Shrine, built in the year 1649 by Tokugawa Iemitsu, stands only a few dozen meters to the left of the temple's main building. Various events are held throughout the year in the Sensoji Temple area. The biggest of them is the Sanja Matsuri, the annual festival of the Asakusa Shrine, held in May. Other events are the Asakusa Samba Carnival in August and the Hagoita-ichi (Hagoita Market) at which decorated wooden paddles used in the traditional game of hanetsuki are sold.", address: "2 Chome-3-1 Asakusa, Taitō-ku, Tōkyō-to 111-0032, Japan", image_url: "https://i.imgur.com/mOypxDt.jpg"})

Activity.create({country: "Japan", name: "Chagohan Tokyo", description: "The Japanese Cuisine Cooking School, CHAGOHAN TOKYO locates in Kappabashi Kitchen Town close to Asakusa. Here is the best place for foodie & learner who would love to cook authentic WASHOKU, to learn the act of preparing and making MATCHA and to taste Japanese SAKE in English or Japanese at seemly clean Japanese detached house.", address: "Japan, 〒111-0035 Tōkyō-to, Taitō-ku, Nishiasakusa, 2 Chome−17, 西浅草2-17-13 1F", image_url: "https://s3-media3.fl.yelpcdn.com/bphoto/TSYb8In2Xc_rMF-ZF4jzCQ/ls.jpg"})

Activity.create({country: "Japan", name: "Tokyo Bike Rentals Yanaka", description: "A concept shop that serves as a gateway to the east side of Tokyo. Located on the former site of the 300-year-old sake purveyor Isego, the shop is a great place to start the day with quality coffee and countless ideas for the day ahead. In addition to offering a colorful range of bicycles for touring the streets of Tokyo, the shop also sells Japanese lifestyle products and serves a selection of sake from Isego.", address: "4 Chome-2-39 Yanaka, Taitō-ku, Tōkyō-to 110-0001, Japan", image_url: "https://d28dpoj42hxr8c.cloudfront.net/files/user/201608031339_6.jpg?v=1470199168"})

Activity.create({country: "Japan", name: "Ueno Park", description: "Ueno Park (上野公園, Ueno Kōen) is a large public park next to Ueno Station in central Tokyo. The park grounds were originally part of Kaneiji Temple, which used to be one of the city's largest and wealthiest temples and a family temple of the ruling Tokugawa clan during the Edo Period. Kaneiji stood in the northeast of the capital to protect the city from evil, much like Enryakuji Temple in Kyoto. Today Ueno Park is famous for the many museums found on its grounds, especially the Tokyo National Museum, the National Museum for Western Art, the Tokyo Metropolitan Art Museum and the National Science Museum. It is also home to Ueno Zoo, Japan's first zoological garden. Additionally, Ueno Park is one of Tokyo's most popular and lively cherry blossom spots with more than 1000 cherry trees lining its central pathway. The cherry blossoms are usually in bloom during late March and early April and attract large numbers of hanami (cherry blossom viewing) parties.", address: "５-20 Uenokōen, Taitō-ku, Tōkyō-to 110-0007, Japan", image_url: "https://i.redd.it/5ojcbi5rktr21.jpg"})

Activity.create({country: "Japan", name: "Ichiran Ramen", description: "Ichiran is one of the most popular ramen restaurants in Tokyo especially among foreign visitors, and the Ichiran in Shibuya is the most-visited branch where many people make a long line in front of the restaurant all the time. Ichiran Ramen (一蘭) is one of the most famous Tonkotsu (pork-based broth) ramen restaurants in Japan. Ichiran has pursued the ultimate Tonkotsu ramen since it was founded over half a century ago in Fukuoka Prefecture, home to Tonkotsu ramen. Its ramen tastes milky and sweet, mixed with smooth-thin noodles and topped with sliced pork and their original spicy red sauce.", address: "Japan, 〒111-0032 Tōkyō-to, Taitō-ku, Asakusa, 1 Chome−1−16 HK浅草ビル", image_url: "https://www.vanguardvoyager.com/wp-content/uploads/2017/08/Ichiran-Ramen_06.jpg"})

Activity.create({country: "Japan", name: "Okonomiyaki Kiji", description: "The Okonomiyaki restaurant called Kiji is extremely well-known and well-loved in Osaka. It's one of the best in the city, serving okonomiyaki (Japanese savory pancake), Osaka's most popular cuisine. The same great authentic okonomiyaki cuisine is also available in Tokyo at two locations! This article will present the original Osaka location as well as the two newer locations in Tokyo.", address: "Japan, 〒100-0005 Tokyo, Chiyoda City, Marunouchi, 2 Chome−7−３ 東京ビルTOKIA B-1F", image_url: "https://media-cdn.tripadvisor.com/media/photo-s/08/d0/58/40/kiji-sky.jpg"})

Activity.create!({country: "Japan", name: "Ramen Museum", description: "The Shinyokohama Raumen Museum (新横浜ラーメン博物館, Shin Yokohama Ra-men Hakubutsukan) is a unique museum about ramen, a very popular Japanese noodle dish which was originally introduced from China. In a gallery on the first floor, the Ramen Museum presents the history of ramen noodles in Japan, including the big success of instant ramen. It displays the variety of noodles, soups, toppings and bowls used across Japan, and shows how the noodles are made. On the two basement floors, visitors can explore a 1:1 replica of some streets and houses of Shitamachi, the old town of Tokyo, of around the year 1958, when the popularity of ramen was rapidly increasing. Nine ramen restaurants can be found there, each featuring a ramen dish from a different region of Japan. For visitors who wish to try multiple ramen dishes, every store offers mini ramen, a small portion of the feature dish. Tickets for the meals are purchased at vending machines in front of each stores before entering.", address: "2 Chome-14-21 Shinyokohama, Kōhoku-ku, Yokohama-shi, Kanagawa-ken 222-0033, Japan", image_url: "http://awoisoak.com/wp-content/uploads/2016/10/dsc00533_lzn_resized.jpg"})

# activities = Activity.all

# activities.each do |activity|
#   Image.create!(
#     url: activity.image_url,
#     activity_id: activity.id
#   )
# end